RecruitmentQUIZ/Controllers/OptionReponseController.cs
using RecruitmentQUIZ.Models;
using RecruitmentQUIZ.Repositories;
using RecruitmentQUIZ.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecruitmentQUIZ.Controllers
{
    public class OptionReponseController : Controller
    {
        IOptionReponse ioptionReponse = new OptionReponseEntityFrameworkRepo();
        IQuestion  iquestion = new QuestionEntityFrameworkRepo();
        IReponseQuest ireponseQuest = new ReponseEntityFrameworkRepo();

        // GET: OptionReponse
        public ActionResult Index(string id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login", "Login");
            }

            Session["questionid"] = id;
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            Question myQuestion = new Question();
            myQuestion = iquestion.GetQuestion(int.Parse(id));
            model.LaQuestion = myQuestion;
            model.OptionReponses = myQuestion.OptionReponses;
            model.SelectedOptionReponse = null;
            return View(model);
        }

        [HttpPost]
        public ActionResult New(string id)
        {
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            Question myQuestion = new Question();
            myQuestion = iquestion.GetQuestion(int.Parse(id));
            model.LaQuestion = myQuestion;
            model.OptionReponses = myQuestion.OptionReponses;
            model.SelectedOptionReponse = null;
            model.DisplayMode = "WriteOnly";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Insert(OptionReponse obj)
        {
            obj.QuestionID = int.Parse(Session["questionid"].ToString());
            ioptionReponse.AjouterOptionReponse(obj);
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            Question myQuestion = ioptionReponse.GetQuestionByOptionReponseID(obj.OptionReponseID);
            model.LaQuestion = myQuestion;
            model.OptionReponses = myQuestion.OptionReponses.ToList();
            model.SelectedOptionReponse = obj;
            model.DisplayMode = "ReadOnly";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Select(string id)
        {
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            Question myQuestion = ioptionReponse.GetQuestionByOptionReponseID(int.Parse(id));
            model.LaQuestion = myQuestion;
            model.OptionReponses = myQuestion.OptionReponses.ToList();
            model.SelectedOptionReponse = myQuestion.OptionReponses.ToList().FirstOrDefault(x => x.OptionReponseID.ToString() == id);
            model.DisplayMode = "ReadOnly";
            return View("Index", model);

        }

        [HttpPost]
        public ActionResult Edit(string id)
        {
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            Question myQuestion  = ioptionReponse.GetQuestionByOptionReponseID(int.Parse(id));
            model.LaQuestion = myQuestion;
            model.OptionReponses = myQuestion.OptionReponses.ToList();
            model.SelectedOptionReponse = myQuestion.OptionReponses.ToList().FirstOrDefault(x => x.OptionReponseID.ToString() == id);
            model.DisplayMode = "ReadWrite";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Update(OptionReponse obj)
        {
            OptionReponse existing = ioptionReponse.GetOptionReponse(obj.OptionReponseID);
            ioptionReponse.UpdateOptionReponse(obj);
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            Question myQuestion = ioptionReponse.GetQuestionByOptionReponseID(obj.OptionReponseID);
            model.LaQuestion = myQuestion;
            model.OptionReponses = myQuestion.OptionReponses.ToList();
            model.SelectedOptionReponse = existing;
            model.DisplayMode = "ReadOnly";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Desactiver(string id)
        {
            // A IMPLEMENTER
            QuestionDetailsViewModel model = new QuestionDetailsViewModel();
            model.LaQuestion = ioptionReponse.GetQuestionByOptionReponseID(int.Parse(id));
            model.SelectedOptionReponse = null;
            model.DisplayMode = "";
            return View("Index", model);
        }

        public ActionResult Reponse(string id)
        {
            Question quest = iquestion.GetQuestion(int.Parse(id));
            return View(quest);
        }

        public JsonResult SaveQuestionAnswer(QuestionResponse questionResponse)
        {
            List<string> LstLibelleOptionReponse  = new List<string>(); 

            Question myQuest = iquestion.GetQuestion(int.Parse(questionResponse.QuestionID));
            if (!myQuest.EstMultiChoix)
            {
                string lblresponse = ioptionReponse.GetOptionReponse(int.Parse(questionResponse.LstOptionId)).Libelle;
                LstLibelleOptionReponse.Add(lblresponse);
            }
            else
            { 
                string[] tbOptID = questionResponse.LstOptionId.Split('_');
                for (int i = 0; i < tbOptID.Length; i++)
                {
                    if (!string.IsNullOrEmpty(tbOptID[i]))
                    {
                        LstLibelleOptionReponse.Add(ioptionReponse.GetOptionReponse(int.Parse(tbOptID[i])).Libelle);
                    }
                }
            }

            ireponseQuest.AddUpdateReponse(questionResponse.QuestionID, LstLibelleOptionReponse);

            return Json(data: new { message = "Data Successfully Added.", success = true }, JsonRequestBehavior.AllowGet);
        }

        public class QuestionResponse
        {
            public string QuestionID { get; set; }
            public string LstOptionId { get; set; }
        }

    }
}

RecruitmentQUIZ/Controllers/ProjetController.cs
using RecruitmentQUIZ.Models;
using RecruitmentQUIZ.Repositories;
using RecruitmentQUIZ.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecruitmentQUIZ.Controllers
{
    public class ProjetController : Controller
    {
        IProjet iprojet = new ProjetEntityFrameworkRepo();
        // GET: Projet
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login", "Login");
            }

            ProjetsViewModel model = new ProjetsViewModel();
            model.Projets = iprojet.GetAllProjets();
            model.SelectedProjet = null;
            return View(model);
        }

        [HttpPost]
        public ActionResult New()
        {
            ProjetsViewModel model = new ProjetsViewModel();
            model.Projets = iprojet.GetAllProjets();
            model.SelectedProjet = null;
            model.DisplayMode = "WriteOnly";
            return View("Index", model);
        }


        [HttpPost]
        public ActionResult Insert(Projet obj)
        {          
              iprojet.AjouterProjet(obj);               
              ProjetsViewModel model = new ProjetsViewModel();
              model.Projets = iprojet.GetAllProjets();
              model.SelectedProjet = iprojet.GetProjet(obj.ProjectID);
              model.DisplayMode = "ReadOnly";
              return View("Index", model);            
        }


        [HttpPost]
        public ActionResult Select(string id)
        {           
            ProjetsViewModel model = new ProjetsViewModel();
            model.Projets = iprojet.GetAllProjets();
            model.SelectedProjet = iprojet.GetProjet(int.Parse(id));
            model.DisplayMode = "ReadOnly";
            return View("Index", model);
            
        }

        [HttpPost]
        public ActionResult Edit(string id)
        {
            ProjetsViewModel model = new ProjetsViewModel();
            model.Projets = iprojet.GetAllProjets();
            model.SelectedProjet = iprojet.GetProjet(int.Parse(id));
            model.DisplayMode = "ReadWrite";
            return View("Index", model);            
        }

        [HttpPost]
        public ActionResult Update(Projet obj)
        {
            Projet existing = iprojet.GetProjet(obj.ProjectID);
            iprojet.UpdateProjet(obj);
            ProjetsViewModel model = new ProjetsViewModel();
            model.Projets = iprojet.GetAllProjets();

            model.SelectedProjet = existing;
            model.DisplayMode = "ReadOnly";
            return View("Index", model);            
        }


        [HttpPost]
        public ActionResult Delete(string id)
        {
            iprojet.SupprimerProjet(iprojet.GetProjet(int.Parse(id)));
            ProjetsViewModel model = new ProjetsViewModel();
            model.Projets = iprojet.GetAllProjets();

            model.SelectedProjet = null;
            model.DisplayMode = "";
            return View("Index", model);
            
        }       
    }
}

RecruitmentQUIZ/Controllers/QuestionController.cs
using RecruitmentQUIZ.Models;
using RecruitmentQUIZ.Repositories;
using RecruitmentQUIZ.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecruitmentQUIZ.Controllers
{
    public class QuestionController : Controller
    {
        IQuestion iquestion = new QuestionEntityFrameworkRepo();
        IProjet iprojet = new ProjetEntityFrameworkRepo();
        // GET: Question
        public ActionResult Index(string id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Login", "Login");
            }

            Session["projetid"] = id;
            ProjetDetailsViewModel model = new ProjetDetailsViewModel();
            Projet myProjet = new Projet();
            myProjet = iprojet.GetProjet(int.Parse(id));
            model.LeProjet = myProjet;
            model.Questions = myProjet.Questions;
            model.SelectedQuestion = null;
            return View(model);
        }


        [HttpPost]
        public ActionResult New(string id)
        {
            ProjetDetailsViewModel model = new ProjetDetailsViewModel();
            Projet myProjet = new Projet();
            myProjet = iprojet.GetProjet(int.Parse(id));
            model.LeProjet = myProjet;
            model.Questions = myProjet.Questions;
            model.SelectedQuestion = null;
            model.DisplayMode = "WriteOnly";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Insert(Question obj)
        {
            obj.ProjetID = int.Parse(Session["projetid"].ToString());
            iquestion.AjouterQuestion(obj);
            ProjetDetailsViewModel model = new ProjetDetailsViewModel();            
            Projet myProjet = iquestion.GetProjetByQuestionID(obj.QuestionID);
            model.LeProjet = myProjet;
            model.Questions = myProjet.Questions.ToList();
            model.SelectedQuestion = obj;
            model.DisplayMode = "ReadOnly";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Select(string id)
        {
            ProjetDetailsViewModel model = new ProjetDetailsViewModel();
            Projet myProjet = iquestion.GetProjetByQuestionID(int.Parse(id));
            model.LeProjet = myProjet;
            model.Questions = myProjet.Questions.ToList();
            model.SelectedQuestion = myProjet.Questions.ToList().FirstOrDefault(x =>x.QuestionID.ToString()== id);
            model.DisplayMode = "ReadOnly";
            return View("Index", model);

        }

        [HttpPost]
        public ActionResult Edit(string id)
        {
            ProjetDetailsViewModel model = new ProjetDetailsViewModel();
            Projet myProjet = iquestion.GetProjetByQuestionID(int.Parse(id));
            model.LeProjet = myProjet;
            model.Questions = myProjet.Questions.ToList();
            model.SelectedQuestion = myProjet.Questions.ToList().FirstOrDefault(x => x.QuestionID.ToString() == id);
            model.DisplayMode = "ReadWrite";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Update(Question obj)
        {
            Question existing = iquestion.GetQuestion(obj.QuestionID);
            iquestion.UpdateQuestion(obj);
            ProjetDetailsViewModel model = new ProjetDetailsViewModel();
            Projet myProjet = iquestion.GetProjetByQuestionID(obj.QuestionID);
            model.LeProjet = myProjet;
            model.Questions = myProjet.Questions.ToList();
            model.SelectedQuestion = existing;
            model.DisplayMode = "ReadOnly";
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult Desactiver(string id)
        {
           // A IMPLEMENTER

            ProjetDetailsViewModel model = new ProjetDetailsViewModel();
            model.LeProjet = iquestion.GetProjetByQuestionID(int.Parse(id));
            model.SelectedQuestion = null;
            model.DisplayMode = "";
            return View("Index", model);

        }
              
       
    }
}

RecruitmentQUIZ/Views/Shared/EditOptionReponse.cshtml
@model RecruitmentQUIZ.Models.OptionReponse

@using (Html.BeginForm("Update", "OptionReponse", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr style="visibility:hidden">
			<td> Option Reponse ID : @Html.TextBoxFor(m => m.OptionReponseID, new { @readonly = "readonly" })</td>
			<td> Question ID : @Html.TextBoxFor(m => m.QuestionID, new { @readonly = "readonly" })</td>
		</tr>		
		<tr>
			<td> Libellé :</td>
			<td>@Html.TextBoxFor(m => m.Libelle, htmlAttributes: new { @class = "form-control" })  </td>
		</tr>
				
		<tr>
			<td colspan="2">
				<input type="submit" value="Edit" formaction="/OptionReponse/update" class="btn btn-success" />
				<input type="submit" value="Cancel" formaction="/OptionReponse/index/@Session["questionid"].ToString()" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/EditProjet.cshtml
@model RecruitmentQUIZ.Models.Projet

@using (Html.BeginForm("Update", "Projet", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr>
			<td> Projet ID :</td>
			<td>@Html.TextBoxFor(m => m.ProjectID, new { @readonly="readonly" })  </td>
		</tr>
		<tr>
			<td> Libellé :</td>
			<td>@Html.TextBoxFor(m => m.Libelle, htmlAttributes: new { @class ="form-control"})  </td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="Edit" formaction="/Projet/update" class="btn btn-success" />
				@*<input type="submit" value="Cancel" formaction="/Projet/cancel/@Model.ProjectID" class="btn btn-default"/>*@
				<input type="submit" value="Cancel" formaction="/Projet/index" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/EditQuestion.cshtml
@model RecruitmentQUIZ.Models.Question

@using (Html.BeginForm("Update", "Question", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr style="visibility:hidden">
			<td> Question ID : @Html.TextBoxFor(m => m.QuestionID, new { @readonly = "readonly" })</td>
			<td> Projet ID : @Html.TextBoxFor(m => m.ProjetID, new { @readonly = "readonly" })  </td>
		</tr>		
		<tr>
			<td> Libellé :</td>
			<td>@Html.TextBoxFor(m => m.Libelle, htmlAttributes: new { @class = "form-control" })  </td>
		</tr>

		<tr>
			<td> Type de réponse :</td>
			<td>
				@Html.DropDownListFor(model => model.EstMultiChoix, new List<SelectListItem> {
				new SelectListItem{Text="Multiple Reponses", Value="True"},
							  new SelectListItem{Text="Unique Reponse", Value="False"}}, "Mode de réponse", htmlAttributes: new { @class = "form-control" })
			</td>
		</tr>

		<tr>
			<td colspan="2">
				<input type="submit" value="Edit" formaction="/Question/update" class="btn btn-success" />
				<input type="submit" value="Cancel" formaction="/Question/index/@Session["projetid"].ToString()" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/InsertProjet.cshtml
@model RecruitmentQUIZ.Models.Projet

@using (Html.BeginForm("Insert", "Projet", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr>
			<td> Projet ID :</td>
			<td>@Html.TextBoxFor(m => m.ProjectID, new { @readonly="readonly" })  </td>
		</tr>
		<tr>
			<td> Libellé :</td>
			<td>@Html.TextBoxFor(m => m.Libelle, htmlAttributes: new { @class ="form-control"})  </td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="Save" formaction="/Projet/insert" class="btn btn-success" />
				<input type="submit" value="Cancel" formaction="/Projet/index" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/InsertQuestion.cshtml
@model RecruitmentQUIZ.Models.Question

@using (Html.BeginForm("Insert", "Question", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr style="visibility:hidden">
			<td> Projet ID :</td>
			<td>@Html.TextBoxFor(m => m.ProjetID, new {@Value =  Session["projetid"].ToString(), @readonly = "readonly" })  </td>
		</tr>
		
		<tr>
			<td> Libellé :</td>
			<td>@Html.TextBoxFor(m => m.Libelle, htmlAttributes: new { @class = "form-control" })  </td>
		</tr>
		<tr>
			<td> Type de réponse :</td>
			<td>
				@Html.DropDownListFor(model => model.EstMultiChoix, new List<SelectListItem> {
				new SelectListItem{Text="Multiple Reponses", Value="True"},
							  new SelectListItem{Text="Unique Reponse", Value="False"}}, "Mode de réponse", htmlAttributes: new { @class = "form-control" })
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="Save" formaction="/Question/insert" class="btn btn-success" />
				<input type="submit" value="Cancel" formaction="/Question/index/@Session["projetid"].ToString()" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/ShowOptionReponse.cshtml
@model RecruitmentQUIZ.Models.OptionReponse

@using (Html.BeginForm("Edit", "OptionReponse", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr style="visibility:hidden">
			<td colspan="2"> Question ID : @Model.QuestionID</td>
		</tr>		
		<tr>
			<td> Libellé :</td>
			<td>@Model.Libelle</td>
		</tr>
		
		<tr>
			<td colspan="2">
				<input type="submit" value="Edit" formaction="/OptionReponse/edit/@Model.OptionReponseID" class="btn btn-success" />
				<input type="submit" value="Cancel" formaction="/OptionReponse/index/@Model.Question.QuestionID" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/ShowProjet.cshtml
@model RecruitmentQUIZ.Models.Projet

@using (Html.BeginForm("Edit","Projet", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr>
			<td> Projet ID :</td>
			<td>@Model.ProjectID</td>
		</tr>
		<tr>
			<td> Libellé :</td>
			<td>@Model.Libelle</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="Edit" formaction="/Projet/edit/@Model.ProjectID" class="btn btn-success"/>
				<input type="submit" value="Cancel" formaction="/Projet/index" class="btn btn-default"/>
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/ShowQuestion.cshtml
@model RecruitmentQUIZ.Models.Question

@using (Html.BeginForm("Edit", "Question", FormMethod.Post))
{
	<table class="table table-condensed">
		<tr style="visibility:hidden">
			<td> Projet ID : @Model.ProjetID</td>
			<td> Question ID : @Model.QuestionID</td>
		</tr>		
		<tr>
			<td> Libellé :</td>
			<td>@Model.Libelle</td>
		</tr>
		<tr>
			<td> Type réponse :</td>
			@{
				string typeR = string.Empty;

				if (Model.EstMultiChoix == true)
				{
					typeR = "Multiples Réponses";
				}
				else
				{
					typeR = "Unique Réponse";
				}
			}

			<td>@typeR</td>

		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="Edit" formaction="/Question/edit/@Model.QuestionID" class="btn btn-success" />
				<input type="submit" value="Cancel" formaction="/Question/index/@Model.Projet.ProjectID" class="btn btn-default" />
			</td>
		</tr>
	</table>
}

RecruitmentQUIZ/Views/Shared/_Layoutadmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Administration</title>
    <!-- BOOTSTRAP STYLES-->
    <link href="~/Content/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="~/Content/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- CUSTOM STYLES-->
    <link href="~/Content/assets/css/custom.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />


</head>
<body>

    <div id="wrapper">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="adjust-nav">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="~/Content/assets/img/mylogo.png" />
                    </a>

                </div>

                <span class="logout-spn">

                    @Html.ActionLink("Logout", "Logout", "Login")

                </span>
            </div>
        </div>
        <!-- /. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li id="1" class="active-link">
                        <a href="@Url.Action("IndexAdmin", "Home")"><i class="fa fa-desktop "></i>Dashboard @*<span class="badge">Included</span>*@</a>
                    </li>
                    <li id="2">
                        <a href="@Url.Action("Index", "Projet")"><i class="fa fa-table "></i>Projets  @*<span class="badge">Included</span>*@</a>
                    </li>
                    <li id="3">
                        <a href="@Url.Action("Candidats", "Home")"><i class="fa fa-edit "></i>Candidats  @*<span class="badge">Included</span>*@</a>
                    </li>
                    <li id="4">
                        <a href="@Url.Action("Resultats", "Home")"><i class="fa fa-bar-chart-o"></i>Resultats  @*<span class="badge">Included</span>*@</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">

                @RenderBody()

            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <div class="footer">


        <div class="row">
            <div class="col-lg-12">
                &copy;  2020 quizSystem | Design by: <a href="#" style="color:#fff;" target="_blank">www.electronic-management.com</a>
            </div>
        </div>
    </div>


    <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="~/Content/assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="~/Content/assets/js/custom.js"></script>

   
</body>


</html>

RecruitmentQUIZ/Views/Shared/_Layoutcnx.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />    
    <title>Em-QUIZ</title>
    <style type="text/css">
        body {
            margin: 0;
            padding: 0;
            background: url('../../Content/images/bk1.jpg') no-repeat;
            background-size: cover;
            background-attachment: fixed;
        }

        .login-box {
            width: 320px;
            height: 420px;
            background: rgba(0,0,0, 0.5);
            color: #fff;
            top: 50%;
            left: 50%;
            position: absolute;
            transform: translate(-50%, -50%);
            box-sizing: border-box;
            padding: 70px 30px;
        }

        .avatar {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            position: absolute;
            top: -50px;
            left: calc(50% - 50px);
        }

        h1 {
            margin: 0;
            padding: 0 0 20px;
            text-align: center;
            font-size: 22px;
        }

        .login-box p {
            margin: 0;
            padding: 0;
            font-weight: bold;
        }

        .login-box input {
            width: 100%;
            margin-top: 20px;
            margin-bottom: 20px;
        }

            .login-box input[type="text"], input[type="password"] {
                border: none;
                border-bottom: 1px solid #fff;
                background: transparent;
                outline: none;
                height: 40px;
                height: 40%;
                color: #fff;
                font-size: 16px;
            }

            .login-box input[type="submit"] {
                border: none;
                outline: none;
                height: 40px;
                background: #1c8adb;
                color: #fff;
                font-size: 18px;
                border-radius: 20px;
            }

                .login-box input[type="submit"]:hover {
                    cursor: pointer;
                    background: #ECBF3D;
                    color: #000;
                }

        .login-box a {
            text-decoration: none;
            font-size: 14px;
            color: #fff;
        }

            .login-box a:hover {
                color: #ECBF3D;
            }
    </style>
</head>
<body>
    <div class="login-box">
        <img src="~/Content/images/avatar.png" class="avatar" alt="Alternate Text" />
        <h1>Login Here</h1>
        @RenderBody()
    </div>
</body>
</html>

RecruitmentQUIZ/Views/Shared/_LoadCandidatExcelImportFile.cshtml
<style type="text/css">
	.upload-btn-wrapper {
		position: relative;
		overflow: hidden;
		display: inline-block;
	}

	.btnUpload {
		border: 2px solid gray;
		color: gray;
		background-color: white;
		padding: 8px 20px;
		border-radius: 8px;
		font-size: 20px;
		font-weight: bold;
	}

	.upload-btn-wrapper input[type=file] {
		font-size: 100px;
		position: absolute;
		left: 0;
		top: 0;
		opacity: 0;
	}
</style>


@using (Html.BeginForm("ImportExcel", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

	<div class="modal-content">
		<div class="modal-header">
			<button id="btnImport" type="button" class="close" data-dismiss="modal">
				×
			</button>
			<h4 class="modal-title">Candidat(s) du projet</h4>
		</div>
		<div class="modal-body" style="margin-bottom: 4rem">
			<form>
				<div class="form-group text-right">
					<a  href="@Url.Action("Download", "Home")">Télécharger un modèle</a>
				</div>
				<hr />
				<div class="form-group">
					<div class="col-md-4">
						<label for="inputname">Fichier à charger</label>
					</div>
					<div class="col-md-8">

						<div class="upload-btn-wrapper">
							<button class="btnUpload">Upload a file</button>
							<input type="file" id="FileUpload1" name="FileUpload1" />
						</div>

					</div>
				</div>
			</form>
		</div>
		<div class="modal-footer">
			<input type="submit" id="Submit" name="Submit" value="Valider" class="btn btn-primary" />
		</div>
	</div>

}